-- left 엿다..
SELECT ID, IFNULL(CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
      FROM ECOLI_DATA
      WHERE PARENT_ID IS NOT NULL
      GROUP BY PARENT_ID) AS C
    ON E.ID = C.PARENT_ID
ORDER BY ID

 
    
