reviews:
  review_status: true
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - study

language: ko

path_filters:
  - "**/*.js"
  - "!README.md"
  - "!.coderabbit.yaml"
  
path_instructions:
  - path: "**/*.js"
    instructions: |
      JavaScript 코드만 리뷰하세요.

  - path: "**/*.md"
    instructions: |
      리뷰하지 마세요.
